"""Read-only exploration API over an indexed Smritikosh database."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Final

import duckdb

from smritikosh.models import SearchResult

if TYPE_CHECKING:
    from smritikosh.ports.embedder import Embedder

__all__ = [
    "IndexInfo",
    "IndexedChunk",
    "ReadOnlyExplorer",
    "SearchOptions",
]

_NON_PRODUCTION_PATH_PENALTY: Final[float] = 0.8
_TEST_INTENT_PATTERN: Final[re.Pattern[str]] = re.compile(
    r"(?<!\w)(?:tests?|testing|pytest|unittest|specs?)(?!\w)",
    re.IGNORECASE,
)
_DOCUMENTATION_INTENT_PATTERN: Final[re.Pattern[str]] = re.compile(
    r"(?<!\w)(?:docs?|documentation|readme|markdown|changelog)(?!\w)",
    re.IGNORECASE,
)
_TEST_PATH_SQL: Final[str] = """
    regexp_matches(lower(path), '(^|/)(tests?|__tests__|specs?)(/|$)')
    OR regexp_matches(
        lower(path),
        '(^|/)(test_[^/]*|[^/]*_(test|spec)|'
        || '[^/]*\\.(test|spec))\\.[^/]+$'
    )
"""
_DOCUMENTATION_PATH_SQL: Final[str] = """
    regexp_matches(lower(path), '(^|/)(docs?|documentation)(/|$)')
    OR regexp_matches(lower(path), '(^|/)(readme|changelog)(\\.[^/]*)?$')
    OR regexp_matches(lower(path), '\\.(md|mdx|rst|adoc)$')
"""


@dataclass(frozen=True)
class IndexInfo:
    """Summarize the contents of a Smritikosh index."""

    files: int
    chunks: int
    vectors: int
    dimensions: int | None


@dataclass(frozen=True)
class IndexedChunk:
    """Represent one source chunk stored in the index."""

    chunk_id: str
    path: str
    start_line: int
    end_line: int
    text: str
    chunk_kind: str | None


@dataclass(frozen=True)
class SearchOptions:
    """Configure semantic search scope and result count."""

    top_k: int = 10
    include_paths: tuple[str, ...] = ()
    exclude_paths: tuple[str, ...] = ()


class ReadOnlyExplorer:
    """Explore one Smritikosh index without acquiring a write connection."""

    def __init__(self, db_path: str) -> None:
        """Open an existing index in read-only mode.

        Args:
            db_path: Path to the Smritikosh DuckDB file.
        """
        if not Path(db_path).is_file():
            raise FileNotFoundError(f"Smritikosh index not found: {db_path}")
        self._connection = duckdb.connect(database=db_path, read_only=True)

    def __enter__(self) -> ReadOnlyExplorer:
        return self

    def __exit__(self, *_: object) -> None:
        self.close()

    def close(self) -> None:
        """Close the read-only database connection."""
        self._connection.close()

    def index_info(self) -> IndexInfo:
        """Return index counts and embedding dimensions."""
        counts: dict[str, int] = dict(
            self._connection.execute(
                "SELECT kind, count(*) FROM nodes GROUP BY kind"
            ).fetchall()
        )
        vector_count: int = self._connection.execute(
            "SELECT count(*) FROM vectors"
        ).fetchone()[0]
        dimensions_row: tuple[str] | None = self._connection.execute(
            "SELECT value FROM kv_store WHERE key = 'embedder_dims'"
        ).fetchone()
        dimensions: int | None = (
            int(dimensions_row[0]) if dimensions_row is not None else None
        )
        return IndexInfo(
            files=counts.get("file", 0),
            chunks=counts.get("chunk", 0),
            vectors=vector_count,
            dimensions=dimensions,
        )

    def semantic_search(
        self,
        queries: list[str],
        *,
        embedder: Embedder,
        options: SearchOptions | None = None,
    ) -> list[SearchResult]:
        """Search for chunks using one or more natural-language queries.

        Args:
            queries: Ad hoc semantic queries generated by the caller.
            embedder: Query embedder matching the indexed vectors.
            options: Search count and optional path filters.

        Returns:
            Deduplicated results ranked by their best score across all queries.

        Raises:
            ValueError: If no query is supplied or ``top_k`` is not positive.
            RuntimeError: If the database has no vector index.
        """
        normalized_queries: list[str] = [
            query.strip() for query in queries if query.strip()
        ]
        if not normalized_queries:
            raise ValueError("At least one non-empty query is required")
        options = options or SearchOptions()
        if options.top_k <= 0:
            raise ValueError("top_k must be positive")

        dimensions: int | None = self.index_info().dimensions
        if dimensions is None:
            raise RuntimeError("No vector index found")
        if embedder.dims != dimensions:
            raise RuntimeError(
                f"Embedder dimensions {embedder.dims} do not match index "
                f"dimensions {dimensions}"
            )

        vectors: list[list[float]] = embedder.encode_queries(normalized_queries)
        hits: dict[str, tuple[float, IndexedChunk]] = {}
        for query, vector in zip(normalized_queries, vectors, strict=True):
            for score, chunk in self._search_vector(
                vector=vector,
                dimensions=dimensions,
                options=options,
                test_path_penalty=self._path_penalty(
                    query,
                    intent_pattern=_TEST_INTENT_PATTERN,
                ),
                documentation_path_penalty=self._path_penalty(
                    query,
                    intent_pattern=_DOCUMENTATION_INTENT_PATTERN,
                ),
            ):
                previous: tuple[float, IndexedChunk] | None = hits.get(chunk.chunk_id)
                if previous is None or score > previous[0]:
                    hits[chunk.chunk_id] = (score, chunk)

        ranked: list[tuple[float, IndexedChunk]] = sorted(
            hits.values(), key=lambda hit: hit[0], reverse=True
        )
        return [
            SearchResult(
                path=chunk.path,
                start_line=chunk.start_line,
                end_line=chunk.end_line,
                snippet=chunk.text,
                score=score,
                chunk_kind=chunk.chunk_kind,
            )
            for score, chunk in ranked[: options.top_k]
        ]

    def find_paths(self, pattern: str, *, limit: int = 50) -> list[str]:
        """Find indexed paths containing a case-insensitive substring.

        Args:
            pattern: Substring to find in indexed paths.
            limit: Maximum number of paths to return.

        Returns:
            Matching paths in lexical order.
        """
        self._validate_limit(limit)
        rows: list[tuple[str]] = self._connection.execute(
            """
            SELECT DISTINCT path
            FROM nodes
            WHERE path IS NOT NULL AND contains(lower(path), lower(?))
            ORDER BY path
            LIMIT ?
            """,
            [pattern, limit],
        ).fetchall()
        return [row[0] for row in rows]

    def text_search(
        self,
        text: str,
        *,
        path: str | None = None,
        limit: int = 20,
    ) -> list[IndexedChunk]:
        """Find chunks containing exact text, case-insensitively.

        Args:
            text: Text or symbol name to locate.
            path: Optional exact indexed path.
            limit: Maximum number of chunks to return.

        Returns:
            Matching chunks ordered by path and source line.
        """
        self._validate_limit(limit)
        path_clause: str = " AND path = ?" if path is not None else ""
        parameters: list[str | int] = [text]
        if path is not None:
            parameters.append(path)
        parameters.append(limit)
        rows: list[tuple[str, str, str]] = self._connection.execute(
            f"""
            SELECT id, path, metadata
            FROM nodes
            WHERE kind = 'chunk'
              AND contains(lower(json_extract_string(metadata, '$.text')), lower(?))
              {path_clause}
            ORDER BY path, CAST(json_extract(metadata, '$.start_line') AS INTEGER)
            LIMIT ?
            """,  # noqa: S608
            parameters,
        ).fetchall()
        return [self._to_chunk(row) for row in rows]

    def get_chunks(
        self,
        path: str,
        *,
        start_line: int | None = None,
        end_line: int | None = None,
    ) -> list[IndexedChunk]:
        """Return chunks from one indexed path, optionally overlapping a line range.

        Args:
            path: Exact indexed source path.
            start_line: Optional first line of the desired range.
            end_line: Optional last line of the desired range.

        Returns:
            Chunks ordered by their starting line.

        Raises:
            ValueError: If a supplied line number is not positive or the range
                is reversed.
        """
        self._validate_line_range(start_line=start_line, end_line=end_line)
        clauses: list[str] = ["kind = 'chunk'", "path = ?"]
        parameters: list[str | int] = [path]
        if start_line is not None:
            clauses.append("CAST(json_extract(metadata, '$.end_line') AS INTEGER) >= ?")
            parameters.append(start_line)
        if end_line is not None:
            clauses.append(
                "CAST(json_extract(metadata, '$.start_line') AS INTEGER) <= ?"
            )
            parameters.append(end_line)
        where_clause: str = " AND ".join(clauses)
        rows: list[tuple[str, str, str]] = self._connection.execute(
            f"""
            SELECT id, path, metadata
            FROM nodes
            WHERE {where_clause}
            ORDER BY CAST(json_extract(metadata, '$.start_line') AS INTEGER)
            """,  # noqa: S608
            parameters,
        ).fetchall()
        return [self._to_chunk(row) for row in rows]

    def _search_vector(
        self,
        *,
        vector: list[float],
        dimensions: int,
        options: SearchOptions,
        test_path_penalty: float,
        documentation_path_penalty: float,
    ) -> list[tuple[float, IndexedChunk]]:
        clauses: list[str] = ["n.kind = 'chunk'"]
        parameters: list[object] = [vector]
        if options.include_paths:
            include_clause: str = " OR ".join(
                "n.path LIKE ?" for _ in options.include_paths
            )
            clauses.append(f"({include_clause})")
            parameters.extend(options.include_paths)
        for pattern in options.exclude_paths:
            clauses.append("n.path NOT LIKE ?")
            parameters.append(pattern)
        parameters.extend([test_path_penalty, documentation_path_penalty])
        parameters.append(options.top_k)
        where_clause: str = " AND ".join(clauses)
        rows: list[tuple[str, str, str, float]] = self._connection.execute(
            self._vector_search_sql(
                dimensions=dimensions,
                where_clause=where_clause,
            ),
            parameters,
        ).fetchall()
        return [(row[3], self._to_chunk(row[:3])) for row in rows]

    @staticmethod
    def _path_penalty(query: str, *, intent_pattern: re.Pattern[str]) -> float:
        """Return full weight when a query explicitly requests a path category."""
        if intent_pattern.search(query):
            return 1.0
        return _NON_PRODUCTION_PATH_PENALTY

    @staticmethod
    def _vector_search_sql(*, dimensions: int, where_clause: str) -> str:
        """Build the vector query with production-first score adjustments."""
        return f"""
            WITH candidates AS (
                SELECT n.id, n.path, n.metadata,
                       array_cosine_similarity(
                           v.vector, ?::FLOAT[{dimensions}]
                       ) AS raw_score
                FROM vectors AS v
                JOIN nodes AS n ON n.id = v.chunk_id
                WHERE {where_clause}
            )
            SELECT id, path, metadata,
                   CASE
                       WHEN ({_TEST_PATH_SQL})
                       THEN raw_score - ((1.0 - ?) * abs(raw_score))
                       WHEN ({_DOCUMENTATION_PATH_SQL})
                       THEN raw_score - ((1.0 - ?) * abs(raw_score))
                       ELSE raw_score
                   END AS score
            FROM candidates
            ORDER BY score DESC
            LIMIT ?
        """  # noqa: S608

    @staticmethod
    def _to_chunk(row: tuple[str, str, str]) -> IndexedChunk:
        metadata: dict[str, object] = json.loads(row[2])
        return IndexedChunk(
            chunk_id=row[0],
            path=row[1],
            start_line=int(metadata["start_line"]),
            end_line=int(metadata["end_line"]),
            text=str(metadata["text"]),
            chunk_kind=(
                str(metadata["chunk_kind"])
                if metadata.get("chunk_kind") is not None
                else None
            ),
        )

    @staticmethod
    def _validate_limit(limit: int) -> None:
        if limit <= 0:
            raise ValueError("limit must be positive")

    @staticmethod
    def _validate_line_range(
        *,
        start_line: int | None,
        end_line: int | None,
    ) -> None:
        if start_line is not None and start_line <= 0:
            raise ValueError("start_line must be positive")
        if end_line is not None and end_line <= 0:
            raise ValueError("end_line must be positive")
        if start_line is not None and end_line is not None and start_line > end_line:
            raise ValueError("start_line cannot be greater than end_line")
